export function panel() {
  const nonce=crypto.randomUUID().replaceAll('-','');
  const html=`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Penghubung Chrome</title>
  <style nonce="${nonce}">body{font:16px system-ui;background:#f1f7f5;color:#15382e;max-width:850px;margin:auto;padding:24px}section{background:white;padding:22px;border-radius:14px;margin:18px 0}button,input,select{font:inherit;padding:12px;margin:5px;max-width:100%;box-sizing:border-box}button{background:#16674f;color:white;border:0;border-radius:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere}small{color:#476058}</style>
  <h1>Penghubung Chrome</h1><p>Gunakan Chrome ponsel Anda dengan izin yang dapat dicabut.</p>
  <section id="login"><h2>Masuk pemilik</h2><input id="password" type="password" placeholder="Kata sandi instalasi" autocomplete="current-password"><button id="signIn">Masuk</button></section>
  <section id="controls" hidden><h2>Perangkat Anda</h2><button id="refresh">Perbarui daftar</button><select id="devices"><option value="">Pilih perangkat secara eksplisit</option></select><button id="status">Periksa status</button><button id="revoke">Cabut perangkat terpilih</button><pre id="layers"></pre><h2>Pendaftaran baru</h2><button id="enroll">Buat token 5 menit, sekali pakai</button><pre id="enrollment"></pre><small>Salin token hanya ke APK Anda. Pairing Wireless Debugging dilakukan terpisah di ponsel.</small><h2>Koneksi MCP</h2><p id="mcp"></p><p>Tambahkan endpoint ini melalui client MCP yang mendukung Streamable HTTP dan OAuth PKCE. Saat diminta, izinkan hanya perangkat yang Anda pilih.</p><button id="logout">Keluar</button></section><p id="notice" role="status"></p>
  <script nonce="${nonce}">
  const $=s=>document.getElementById(s);const api=async(path,data)=>{const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const out=await r.json();if(!r.ok)throw Error(out.error?.code||'Permintaan gagal');return out;};
  const run=f=>async()=>{try{await f();$('notice').textContent='';}catch(e){$('notice').textContent=e.message;}};
  const refresh=async()=>{const out=await api('/api/devices');const selected=$('devices').value;$('devices').replaceChildren(new Option('Pilih perangkat secara eksplisit',''));for(const d of out.devices){if(!d.revoked)$('devices').add(new Option(d.alias,d.deviceId));}if([...$('devices').options].some(o=>o.value===selected))$('devices').value=selected;$('controls').hidden=false;$('login').hidden=true;$('mcp').textContent=location.origin+'/mcp';};
  $('signIn').onclick=run(async()=>{await api('/api/login',{password:$('password').value});$('password').value='';await refresh();const next=new URLSearchParams(location.search).get('next');if(next&&next.startsWith('/oauth/authorize?'))location.assign(next);});
  $('refresh').onclick=run(refresh);$('status').onclick=run(async()=>{if(!$('devices').value)throw Error('Pilih perangkat dahulu');$('layers').textContent=JSON.stringify(await api('/api/status?deviceId='+encodeURIComponent($('devices').value)),null,2);});
  $('enroll').onclick=run(async()=>{const out=await api('/api/enrollment',{});$('enrollment').textContent=out.enrollmentToken+'\\nBerlaku sampai '+new Date(out.expiresAt).toLocaleString('id-ID');});
  $('revoke').onclick=run(async()=>{if(!$('devices').value)throw Error('Pilih perangkat dahulu');if(confirm('Cabut akses perangkat ini? Token APK tidak dapat dipakai kembali.')){await api('/api/revoke',{deviceId:$('devices').value});await refresh();}});
  $('logout').onclick=run(async()=>{await api('/api/logout',{});location.reload();});refresh().catch(()=>{});
  </script></html>`;
  return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`,'Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});
}
